indel_character_matrix_file_path = "/my/path/indel_character_matrix"
cut_positions_file_path = "/my/path/cut_positions"
mutations_file_path = "/my/path/mutations"

asv_stat_file_path = "/my/path/asv_stat"

ref_seq = "TCTACACGCGCGTTCAACCGAGGAAAACTACACACACGTTCAACCACGGTTTTTTACACACGCATTCAACCACGGACTGCTACACACGCACTCAACCGTGGATATTTACATACTCGTTCAACCGTGGATTGTTACACCCGCGTTCAACCAGGGTCAGATACACCCACGTTCAACCGTGGTACTATACTCGGGCATTCAACCGCGGCTTTCTGCACACGCCTACAACCGCGGAACTATACACGTGCATTCACCCGTGGATC"
ref_name = "BC10v0"

