pmh_tr -o CP03_split -c CP03_colors.txt -p PRL CP03_tree_split.txt CP03_labels_split.txt &> CP03_split/results.txt
pmh_tr -o CP04_split -c CP04_colors.txt -p PRL CP04_tree_split.txt CP04_labels_split.txt &> CP04_split/results.txt
pmh_tr -o CP05_split -c CP05_colors.txt -p PRL CP05_tree_split.txt CP05_labels_split.txt &> CP05_split/results.txt
pmh_tr -o CP06_split -c CP06_colors.txt -p PRL CP06_tree_split.txt CP06_labels_split.txt &> CP06_split/results.txt
pmh_tr -o CP07_split -c CP07_colors.txt -p PRL CP07_tree_split.txt CP07_labels_split.txt &> CP07_split/results.txt
pmh_tr -o CP08_split -c CP08_colors.txt -p PRL CP08_tree_split.txt CP08_labels_split.txt &> CP08_split/results.txt
pmh_tr -o CP09_split -c CP09_colors.txt -p PRL CP09_tree_split.txt CP09_labels_split.txt &> CP09_split/results.txt
pmh_tr -o CP10_split -c CP10_colors.txt -p PRL CP10_tree_split.txt CP10_labels_split.txt &> CP10_split/results.txt
pmh_tr -o CP11_split -c CP11_colors.txt -p PRL CP11_tree_split.txt CP11_labels_split.txt &> CP11_split/results.txt
pmh_tr -o CP12_split -c CP12_colors.txt -p PRL CP12_tree_split.txt CP12_labels_split.txt &> CP12_split/results.txt
pmh_tr -o CP13_split -c CP13_colors.txt -p PRL CP13_tree_split.txt CP13_labels_split.txt &> CP13_split/results.txt
pmh_tr -o CP14_split -c CP14_colors.txt -p PRL CP14_tree_split.txt CP14_labels_split.txt &> CP14_split/results.txt
pmh_tr -o CP15_split -c CP15_colors.txt -p PRL CP15_tree_split.txt CP15_labels_split.txt &> CP15_split/results.txt
pmh_tr -o CP16_split -c CP16_colors.txt -p PRL CP16_tree_split.txt CP16_labels_split.txt &> CP16_split/results.txt
pmh_tr -o CP17_split -c CP17_colors.txt -p PRL CP17_tree_split.txt CP17_labels_split.txt &> CP17_split/results.txt
pmh_tr -o CP18_split -c CP18_colors.txt -p PRL CP18_tree_split.txt CP18_labels_split.txt &> CP18_split/results.txt
pmh_tr -o CP19_split -c CP19_colors.txt -p PRL CP19_tree_split.txt CP19_labels_split.txt &> CP19_split/results.txt
pmh_tr -o CP20_split -c CP20_colors.txt -p PRL CP20_tree_split.txt CP20_labels_split.txt &> CP20_split/results.txt
pmh_tr -o CP21_split -c CP21_colors.txt -p PRL CP21_tree_split.txt CP21_labels_split.txt &> CP21_split/results.txt
pmh_tr -o CP22_split -c CP22_colors.txt -p PRL CP22_tree_split.txt CP22_labels_split.txt &> CP22_split/results.txt
pmh_tr -o CP23_split -c CP23_colors.txt -p PRL CP23_tree_split.txt CP23_labels_split.txt &> CP23_split/results.txt
pmh_tr -o CP24_split -c CP24_colors.txt -p PRL CP24_tree_split.txt CP24_labels_split.txt &> CP24_split/results.txt
pmh_tr -o CP25_split -c CP25_colors.txt -p PRL CP25_tree_split.txt CP25_labels_split.txt &> CP25_split/results.txt
pmh_tr -o CP26_split -c CP26_colors.txt -p PRL CP26_tree_split.txt CP26_labels_split.txt &> CP26_split/results.txt
pmh_tr -o CP27_split -c CP27_colors.txt -p PRL CP27_tree_split.txt CP27_labels_split.txt &> CP27_split/results.txt
pmh_tr -o CP28_split -c CP28_colors.txt -p PRL CP28_tree_split.txt CP28_labels_split.txt &> CP28_split/results.txt
pmh_tr -o CP29_split -c CP29_colors.txt -p PRL CP29_tree_split.txt CP29_labels_split.txt &> CP29_split/results.txt
pmh_tr -o CP30_split -c CP30_colors.txt -p PRL CP30_tree_split.txt CP30_labels_split.txt &> CP30_split/results.txt
pmh_tr -o CP31_split -c CP31_colors.txt -p PRL CP31_tree_split.txt CP31_labels_split.txt &> CP31_split/results.txt
pmh_tr -o CP32_split -c CP32_colors.txt -p PRL CP32_tree_split.txt CP32_labels_split.txt &> CP32_split/results.txt
pmh_tr -o CP33_split -c CP33_colors.txt -p PRL CP33_tree_split.txt CP33_labels_split.txt &> CP33_split/results.txt
pmh_tr -o CP34_split -c CP34_colors.txt -p PRL CP34_tree_split.txt CP34_labels_split.txt &> CP34_split/results.txt
pmh_tr -o CP35_split -c CP35_colors.txt -p PRL CP35_tree_split.txt CP35_labels_split.txt &> CP35_split/results.txt
pmh_tr -o CP36_split -c CP36_colors.txt -p PRL CP36_tree_split.txt CP36_labels_split.txt &> CP36_split/results.txt
pmh_tr -o CP37_split -c CP37_colors.txt -p PRL CP37_tree_split.txt CP37_labels_split.txt &> CP37_split/results.txt
pmh_tr -o CP38_split -c CP38_colors.txt -p PRL CP38_tree_split.txt CP38_labels_split.txt &> CP38_split/results.txt
pmh_tr -o CP39_split -c CP39_colors.txt -p PRL CP39_tree_split.txt CP39_labels_split.txt &> CP39_split/results.txt
pmh_tr -o CP40_split -c CP40_colors.txt -p PRL CP40_tree_split.txt CP40_labels_split.txt &> CP40_split/results.txt
pmh_tr -o CP41_split -c CP41_colors.txt -p PRL CP41_tree_split.txt CP41_labels_split.txt &> CP41_split/results.txt
pmh_tr -o CP42_split -c CP42_colors.txt -p PRL CP42_tree_split.txt CP42_labels_split.txt &> CP42_split/results.txt
pmh_tr -o CP43_split -c CP43_colors.txt -p PRL CP43_tree_split.txt CP43_labels_split.txt &> CP43_split/results.txt
pmh_tr -o CP44_split -c CP44_colors.txt -p PRL CP44_tree_split.txt CP44_labels_split.txt &> CP44_split/results.txt
pmh_tr -o CP45_split -c CP45_colors.txt -p PRL CP45_tree_split.txt CP45_labels_split.txt &> CP45_split/results.txt
pmh_tr -o CP46_split -c CP46_colors.txt -p PRL CP46_tree_split.txt CP46_labels_split.txt &> CP46_split/results.txt
pmh_tr -o CP47_split -c CP47_colors.txt -p PRL CP47_tree_split.txt CP47_labels_split.txt &> CP47_split/results.txt
pmh_tr -o CP48_split -c CP48_colors.txt -p PRL CP48_tree_split.txt CP48_labels_split.txt &> CP48_split/results.txt
pmh_tr -o CP49_split -c CP49_colors.txt -p PRL CP49_tree_split.txt CP49_labels_split.txt &> CP49_split/results.txt
pmh_tr -o CP50_split -c CP50_colors.txt -p PRL CP50_tree_split.txt CP50_labels_split.txt &> CP50_split/results.txt
pmh_tr -o CP51_split -c CP51_colors.txt -p PRL CP51_tree_split.txt CP51_labels_split.txt &> CP51_split/results.txt
pmh_tr -o CP52_split -c CP52_colors.txt -p PRL CP52_tree_split.txt CP52_labels_split.txt &> CP52_split/results.txt
pmh_tr -o CP53_split -c CP53_colors.txt -p PRL CP53_tree_split.txt CP53_labels_split.txt &> CP53_split/results.txt
pmh_tr -o CP54_split -c CP54_colors.txt -p PRL CP54_tree_split.txt CP54_labels_split.txt &> CP54_split/results.txt
pmh_tr -o CP55_split -c CP55_colors.txt -p PRL CP55_tree_split.txt CP55_labels_split.txt &> CP55_split/results.txt
pmh_tr -o CP56_split -c CP56_colors.txt -p PRL CP56_tree_split.txt CP56_labels_split.txt &> CP56_split/results.txt
pmh_tr -o CP57_split -c CP57_colors.txt -p PRL CP57_tree_split.txt CP57_labels_split.txt &> CP57_split/results.txt
pmh_tr -o CP58_split -c CP58_colors.txt -p PRL CP58_tree_split.txt CP58_labels_split.txt &> CP58_split/results.txt
pmh_tr -o CP59_split -c CP59_colors.txt -p PRL CP59_tree_split.txt CP59_labels_split.txt &> CP59_split/results.txt
pmh_tr -o CP60_split -c CP60_colors.txt -p PRL CP60_tree_split.txt CP60_labels_split.txt &> CP60_split/results.txt
pmh_tr -o CP61_split -c CP61_colors.txt -p PRL CP61_tree_split.txt CP61_labels_split.txt &> CP61_split/results.txt
